receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  otlphttp:
    # Replace with your Loki server’s private IP and port
    endpoint: "http://10.0.1.15:3100/otlp/v1/logs"

  otlp:
    endpoint: "10.254.0.8:4317"
    tls:
      insecure: true

  debug:
    verbosity: detailed

processors:
  batch:

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]