receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: http://10.254.0.8:3100/otlp

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]